# Site
repository: semicolok/semicolok.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 한준구
title: Software Engineer
email: semicolok@gmail.com
website: semicolok.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: semicolok
github_username: semicolok
# stackoverflow_username: "00000001"
# dribbble_username: semicolok
facebook_username: semicolok
# flickr_username: semicolok
# instagram_username: jameswgrant
linkedin_username: junguhan
# xing_username: jekyll
# pinterest_username: semicolok
# youtube_username: jknyou
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: About Me
about_profile_image: images/profile_1.jpg
about_content: | 
    안녕하세요 한준구입니다.

    2011년에 Java 개발자로 일하기 시작해서 현재는 일본에서 일하고 있습니다.

    Startup, E-Commerce, 일본 IT회사, Internet Bank까지 다양한 경험을 통해 Middleware에서 Application까지 폭 넓은 경험을 가지고 있는 개발자입니다.

    여느 개발자들처럼 신기술에 관심이 많고 배우는 것을 즐깁니다. 하지만 기술보다는 서비스가 더 중요하다고 생각 하는 개발자입니다.

    그 어떤 좋은 기술이라도 서비스에 문제가 생긴다면 그 기술들의 가치는 빛을 보지 못하기 때문에 항상 서비스 관점에서 먼저 생각하고 적합한 기술을 선택하고 충분히 기술을 검증후에 사용하려고 노력하는 개발자 입니다.

    남들 보다 길었던 군생활로 사회생활 시작이 조금 늦었지만, 그 길었던 시간만큼 더 주도적이고 책임감 있는 사람으로 사회생활을 시작하였습니다. 그래서 지금은 빨리 시작한 개발자분들과 비교해 뒤쳐지지 않는 개발자가 되었다고 생각합니다.

    감사합니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 카카오 뱅크 (Kakao Bank)
        link: https://www.kakaobank.com/
        # link_text: boringcompany.com
        sub_title: Software Engineer
        caption: Feb 2020 - Present
        quote: >
          DevOps Platform Team  
        description: | # this will include new lines to allow paragraphs
            - S3기반의 파일 관리 시스템 개발 (MinIO, spring boot, spring security OAuth2.0, gradle, MySQL)
            - 도커 배포 시스템 개발 (Ansible, Jenkins, spring boot, gradle, MongoDB)
            - 계정관리 시스템 개발 (OpenLDAP, spring boot, gradle, Orcacle, MySQL)
      - layout: left
        title: 라쿠텐 (Rakuten, Inc.)
        link: https://www.rakuten.com/
        sub_title: Software Engineer & DevOps Team Leader
        caption: Feb 2017 - Mar 2020
        quote: >
          Network Division  
        description: | 
            - Rakuten Mobile App server 개발 (Java, Spring-boot, Gradle) 
            - CS AI Chabot 개발 (Vaadin, Spring-boot, Maven) 
            - Microservice API 개발 (Spring-cloud, Gradle)
            - Distributed operating system 구축 (DC/OS, Azure, Kubernetes, Istio, GCP)
            - Third party API Integration (KDDI, Docomo, Google)
            - Legacy system migration (Perl and PL/SQL to Java, Spring and JPA)

      - layout: left
        title: 티켓몬스터 (TICKETMONSTER INC.)
        link: https://www.tmon.co.kr/
        sub_title: Software Engineer
        caption: May 2016 - Dec 2016
        quote: >
          Service Development Lab
        description: | 
            - Deal contents part 개발 (Jave, Spring, Maven, AngularJS)
            - “Shoppable project” Back-end 개발 (Java, Spring, Gradle)

      - layout: left
        title: 쿠팡 (Forward Ventures Co.,Ltd)
        link: https://www.coupang.com/
        sub_title: Software Engineer
        caption: Mar 2015 - Apr 2016
        quote: >
          Team Rossetta
        description: | 
            - CS Platform
              - Chatting server 개발(NodeJS, Spring, Gradle)
              - Application server 개발 (Linux, Java, Spring, Gradle)
              - Web client 개발 (JavaScript, handlebars)
            - Biz Platform
              - Application server 개발 (Linux, Java, Spring)
              - Web client 개발 (JavaScript, ReactJS, Handlebars)
              - System migration.

      - layout: left
        title: 소프트웨어인라이프 (Software in Life Inc.)
        link: https://www.docswave.com/
        sub_title: Software Engineer & Solution Part Leader
        caption: Nov 2011 - Mar 2015
        quote: >
          R&D Center
        description: | 
            - System Architecture 설계 (application, technical, data)
            - Application server 개발 (Linux, Java, Spring, Maven, Gradle, Python, django)
            - Web client 개발 (JavaScript, AngularJS)
            - Android 개발

  - title: Skills
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Languages
        description: | 
            Java, Javascript, HTML, Scala, Groovy, Python, SQL, PL/SQL
      - layout: left
        title: Standards / Frameworks
        description: | 
            Spring, Spring-boot, Spring-cloud, Spring-security, Spring-data, Spring-data-redis, Gradle, Maven, SBT, QueryDSL, Hibernate, MyBatis, Ehcache, Servlet, AJAX, JQuery, RESTful, Flyway, Junit, Mockito, Spock, Play framework, Skinny-orm,  Django, Grails, AngularJS, NodeJS, ReactJS
      - layout: left
        title: Web Servers / Application Servers
        description: | 
            Apache, Nginx, Tomcat, Jetty, GlassFish
      - layout: left
        title: Databases
        description: | 
            Oracle, MySQL, MariaDB, Redis, MongoDB, Google Cloud SQL, Google Datastore
      - layout: left
        title: Development / Environment Tools / Techniques
        description: | 
            Git, Subversion, Jenkins, Jira, Google Compute Engine, Google Kubernetes Engine, AWS, Azure, Nexus, JMeter, nGrinder, Pinpoint, DC/OS, Kubernetes, Docker
      

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 백석대학교
        caption: 2003 - 2012
        sub_title: 멀티미디어학 학사 (BSc Multimedia Engineering)
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        # description: | # this will include new lines to allow paragraphs
        #   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

        #   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | 
      취미:
      - Powerlifting
      - Bouldering
      - Traveling

  #     Look at this cool image  
  #     ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
